### ISSUE TITLE
Se requiere la extensión POSIX en Linux

### ISSUE THREAD

**Issue by lonoak** [rediris-es/simplesamlphp-module-idp_installer#13]
Ejecutando el instalador en un Linux (CentOS 7), me aparece el error 'Es necesario que instale las siguientes extensiones PHP: posix.'.

Creo que el problema está localizado en torno a la línea:

https://github.com/rediris-es/simplesamlphp-module-idpinstaller/blob/master/hooks/hook_step1.php#L73

**Comment by adriangmemorandum** [comment]
La extensión POSIX si que es obligatoria para UNIX, se utiliza para obtener información acerca del fichero y proponer un comando para solucionar los posibles problemas de permisos/propietario que pudieran existir.

En Windows esa extensión no existe, ya que POSIX se utiliza unicamente en UNIX: [https://www.php.net/manual/en/intro.posix.php](https://www.php.net/manual/en/intro.posix.php
)

Más adelante en el codigo hacemos una comprobación para ver si existe la funcion POSIX antes de utilizarla. En caso contrario se utilizan valores por defecto. [https://github.com/rediris-es/simplesamlphp-module-idpinstaller/blob/master/hooks/hook_step1.php#L152](https://github.com/rediris-es/simplesamlphp-module-idpinstaller/blob/master/hooks/hook_step1.php#L152)

**Comment by lonoak** [comment]
Justo estaba mirándolo... sí, la requiere este módulo... hecho un vistazo para ver si es posible ponerlo como dependencia en composer (antes de llegar al instalador).

**Comment by lonoak** [comment]
Ok... en el caso de CentOS/RedHat parece que la extensión POSIX va de php73-process.x86_64... he añadido en el composer que compruebe que la extensión esté instalada.
