### ISSUE TITLE
Admin password shouldn't be in plain text

### ISSUE THREAD

**Issue by lonoak** [rediris-es/simplesamlphp-module-idp_installer#2]
SSp support hashed passwords, note to self to fix this:

https://simplesamlphp.org/docs/stable/simplesamlphp-install#section_7

**Comment by lonoak** [comment]
Las opciones disponibles por el momento se pueden ver ejecutando:

https://github.com/simplesamlphp/simplesamlphp/blob/master/bin/pwgen.php

**Comment by adriangmemorandum** [comment]
He modificado el proceso de almacenamiento de la contraseña para que se cifre correctamente siguiendo con los metodos que proporciona SimpleSAMLphp. 

Puedes ver el codigo aqui: 

https://github.com/rediris-es/simplesamlphp-module-idpinstaller/commit/0945e6baddef9425b3ccca29a4100b066eaf64ad

Si prefieres otro algoritmo indicamelo y lo cambio. 

He revisado que este cambio permita a posteriori loguarse correctamente, y funciona OK.

**Comment by adriangmemorandum** [comment]
Tambien he creado un botón que genera una nueva contraseña y un proceso que valida la fuerza de la misma. Es algo que mi anterior compañero tenia en marcha, así que lo he completado. Podrá ser: 
- Muy fuerte
- Fuerte
- Debil
- Muy debil

La fuerza variará del número de caracteres, la existencia de símbolos, mayúsculas, minúsculas y caracteres especiales.

El proceso de generación siempre creará una contraseña que sea fuerte o muy fuerte. 

He quitado el `height: 500px` de la template `stepn`, ya que se estaba asignando un maximo de 500px al contenedor y cuando el formulario ocupaba más de esos 500px el pie de página se solapaba con el contenedor. 

Puedes ver aqui los cambios: https://github.com/rediris-es/simplesamlphp-module-idpinstaller/commit/8b59e4354ddbc14606b1cbd8f85c28f8fa3da353
