### ISSUE TITLE
Añadir usuarios con módulo "exampleAuth:UserPass"

### ISSUE THREAD

**Issue by carlossancho93** [rediris-es/simplesamlphp-module-idp_installer#7]
Realizada la prueba para incluir en el IdP de la máquina virtal de referencia un proveedor local de identidad basado en ficheros locales según documentación proporcionada: 
https://simplesamlphp.org/docs/stable/simplesamlphp-idp#section_3

Se ha configurado el proveedor example-userpass con dos usuarios student y employee con atributos del esquema 
eduPerson.

Se comprueba que aplicando el método de configuración descrito en la documentación, aparece como disponible dicho IdP y autentifica los usuarios configurados localmente.

Posibles usos:
- Fundamentalmente permite ganar experiencia con la administración de IdP, y con el manejo del interfaz gráfico.
- Introduce la posibilidad de incluir atributos de los esquemas y usuarios desde la máquina virtual, sin tener que emplear el interfaz de LDAP que viene incluido.
- Permitiría realizar pruebas sencillas y comprobar el funcionamiento del IdP con varias proveedores.

**Comment by lonoak** [comment]
Un comentario respecto a esto... habría que añadir esta posibilidad (además de las existentes de LDAP y PDO) en el selector de tipos de ~~autenticación~~ `authsource`. Al margen de esto, pienso que los usuarios y credenciales deberían ser generados aleatoriamente, para no incurrir en riesgo de que se reusasen de un IdP a otro...

**Comment by adriangmemorandum** [comment]
En el paso 3 de la instalación, en el combo de seleccion del tipo de fuente de datos, habria que añadir una nueva opción, a la que podriamos llamar "Config" (por ejemplo). Hasta ahi todo OK.

Hay que establecer en detalle el funcionamiento a desarrollar. Por ejemplo. 

¿Habria que generar un número determinado de usuarios? ¿O podemos dejar que el administrador decida cuantos usuarios crear? 

¿Generamos los usuarios y contraseñas aleatoriamente y no permitimos que el administrador pueda modificarlas? ¿Algún patron en especial que deban seguir dichos usuarios y contraseñas?
Podemos dejar que el usuario sea quien cree los usuarios, pero nosotros añadirle un prefijo o sufijo de forma que nos aseguremos que el usuario es único pero a su vez el administrador pueda recordar e identificar dicho usuario con mayor facilidad... o podemos simplemente generar un string aleatoria. Para la contraseña serviría con el código ya implementado para la generación de la contraseña del administrador. 

Podemos ver los distintos roles a utilizar en [este enlace](https://www.feide.no/attribute/edupersonaffiliation). ¿Deberiamos permitir que el administrador pudiera seleccionar cualquiera de esos roles en la creación de cada usuario?¿Solamente vamos a trabajar con ciertos roles?

En [este otro enlace](https://www.feide.no/attributelist) disponemos de los distintos attributos que podemos asignar a los usuarios. Entiendo que sería interesante añadir alguno más, para poder identificar mejor a los usuarios y sus funciones o caracteristicas. Esto requeriría de un input en el formulario por cada atributo que queramos añadir. 

Quedo a espera de comentarios al respecto.

**Comment by lonoak** [comment]
Intento responder a tus preguntas:

> ¿Habria que generar un número determinado de usuarios?

2 es un buen número

> ¿O podemos dejar que el administrador decida cuantos usuarios crear?

Nah...

> ¿Generamos los usuarios y contraseñas aleatoriamente y no permitimos que el administrador pueda modificarlas? 

Siempre podrá hacerlo a posteriori en el authsources.php...

> ¿Algún patron en especial que deban seguir dichos usuarios y contraseñas?

`uNNNNN` (siendo NNNNN un número aleatorio) y una contraseña robusta al azar.

> ¿Deberiamos permitir que el administrador pudiera seleccionar cualquiera de esos roles en la creación de cada usuario?

No, pero habría que crear al menos los [recomendados en SIR2](https://www.rediris.es/sir2/federacion/atributos/).

> ¿Solamente vamos a trabajar con ciertos roles? 

Si te refieres a `eduPersonAffiliation`, podríamos crear uno con `staff` y otro con `faculty`...

**Comment by adriangmemorandum** [comment]
Okey... ¿creas rama para ir avanzando?

**Comment by lonoak** [comment]
creada.

**Comment by adriangmemorandum** [comment]
Creado el commit que implementa esta nueva funcionalidad: https://github.com/rediris-es/simplesamlphp-module-idpinstaller/commit/839fde37e56283f8c11dba0fafe118188c45f121

Lo que se hace es generar dos usuarios aleatorios, con una contraseña segura. Uno de los usuarios con rol de `staff` y otro con rol `faculty`. Los inputs son de solo lectura, así que no se pueden modificar durante el proceso de instalación. Adjunto captura: 

![exampleauth](https://user-images.githubusercontent.com/12030741/43067617-207874bc-8e68-11e8-9355-d410be8b9100.png)

Confirmame si te parece bien así y quieres que haga PR o quieres hacer algun cambio.

**Comment by lonoak** [comment]
Tiene buena pinta... ¿son campos editables? ¿se generan otros atributos aunque no se vean?

**Comment by adriangmemorandum** [comment]
No son campos editables. Ahora mismo son inputs `readonly`. Si quieres que se puedan editar simplemente quito `readonly` y listo. 

En cuanto a los atributos, de momento no se está generando ningun atributo adicional. Solamente lo que ves en la captura. Si quieres que haya algún atributo en particular lo puedo añadir sin problemas. 

O tambien lo puedo preparar para que el administrador pueda añadir (o no) algún atributo adicional de entre una serie de atributos que consideres interesantes. Podriamos añadir un botón de añadir atributo que nos mostraría un selector para elegir el atributo a añadir y un input para darle el valor al atributo.

**Comment by lonoak** [comment]
Read only. Otros atributos, sí, los recomendados en SIR2 que os comentaba...

No es necesario que sean editables.

**Comment by adriangmemorandum** [comment]
Vale, pero entonces yo creo que algunos de ellos al menos si que deberian ser editables ¿no? Veamoslos en detalle, en la columna 'tratamiento' están mis comentarios: 

Nombre | Descripción | Tratamiento
-- | -- | --
commonName | Nombre y apellidos. Puede ser multievaluado, aunque se recomienda un sólo valor. | ¿Generamos un nombre a partir de el rol y el identificador de usuario (por ejemplo? ¿o mejor creamos un input para este campo?
displayName | Nombre y apellidos. | Lo mismo que el campo anterior
eduPersonAffiliation | Un atributo cuyos valores (puede recbir más de uno) están acotados  generalmente por un diccionario, que incluye las distintas afiliaciones  que un sujeto puede tener para con una organización (personal de  administración y servicios de la organización, personal docente,  investigador, estudiante,...). | Ya tratamos este atributo
eduPersonEntitlement | URI (URN o URL) que indica un conjunto de derechos para recursos específicos. | ¿Qué URI deberiamos configurar en este atributo?
eduPersonPrincipalName | Identificador único y persistente de un usuario. | Siendo un identificador único, podriamos utilizar el identificador de usuario (uNNNNN) generado aleatoriamente.
eduPersonScopedAffiliation | Representa la afiliación de una persona con respecto a un determinado dominio de organización. | Consta de una parte que es el rol y otra parte que es el dominio... ¿qué dominio deberiamos asignar aquí?
eduPersonTargetedID | Un atributo persistente, no reasignado, que preserva la privacidad y  es compartido entre un par de entidades que se coordinan entre sí. | Veo que está es la formula para generar este identificador: eduPersonTargetedId= HASH(idUsuario + idDestino + idOrigen + sal). ¿Cual seria el idDestino y el idOrigien?
mail | La dirección de correo electrónico principal de un sujeto. | ¿Deberiamos crear un input para este atributo? ¿O asignamos un mail predefinido?
schacHomeOrganization | Especifica la organización a la que pertenece un sujeto, usando el dominio de la organización. | ¿Qué dominio ponemos aquí?
schacHomeOrganizationType | Tipo de organización. | Segun veo, los valores definidos en españa son los siguientes: university, pri y company. ¿Creamos un select para que se pueda elegir o asignamos uno de forma predeterminada?
schacPersonalUniqueCode | Un código único asociado a un sujeto, que no tiene que  corresponderse necesariamente con ningún otro identificador fuera del  ámbito de los directorios que usen este esquema. El atributo se define  como un URN con el formato: urn:schac:personalUniqueCode:es:rediris:sir:mbid:{\<algor\>}\<hash\>. | ¿Que valores deberiamos rellenar en la parte de algor y hash?
uid | Un identificador corto de usuario, conocido en el ámbito de la organización a la que pertenece el sujeto. | Ya estamos tratando este atributo

**Comment by lonoak** [comment]
Hola, casi mejor tratarlo por correo o en una video que aquí...

**Comment by lonoak** [comment]
Depende de #8

**Comment by adriangmemorandum** [comment]
Bueno, acabo de subir un commit en el que hago algunos avances sobre esto: https://github.com/rediris-es/simplesamlphp-module-idpinstaller/commit/fd2a78151b0ef80f5179cbda10147971e8cdf828

De momento he hecho lo que teniamos claro como hacer. Puedes ver en la siguiente imagen como quedarian los atributos: 

![exampleauth1](https://user-images.githubusercontent.com/12030741/43792144-28bbe408-9a78-11e8-8faa-ac6b0657b405.png)


Faltan los siguientes atributos: 

- eduPersonTargetId: Dijiste que de momento lo obviaramos.
- mail: Necesito saber que email poner, dijiste que pusieramos un email predefinido
- schacHomeOrganizationType: De momento he puesto `university`, pero comentaste que quiza deberias preguntarlo.
- schacPersonalUniqueCode: También tenias que consultar con un compañero.

**Comment by lonoak** [comment]
Tiene buena pinta.

Sobre los atributos que preguntas:

>     eduPersonTargetId: Dijiste que de momento lo obviaramos.

Bueno. De momento no podemos usar el `core:TargetedID`, que sería lo suyo. Pero pienso que podemos consensuar una formula utilizando el módulo hub&spoke que se instala...
 
>    mail: Necesito saber que email poner, dijiste que pusieramos un email predefinido

Tipo (parecido o igual) a `eduPersonPrincipalName` estaría bien.

>    schacHomeOrganizationType: De momento he puesto university, pero comentaste que quiza deberias preguntarlo.

Bueno, tenemos varios valores disponibles [por aquí](https://www.rediris.es/rid/urn/schac/urnreg/browser/browser.php), pero quizá sólo lo pondría como comentario en la configuración generada que el valor debe defiirse según el diccionario en ese enlace...

>    schacPersonalUniqueCode: También tenias que consultar con un compañero.

De momento podemos hacerlo de manera parecida a [como se hacía en SIR](https://www.rediris.es/sir/docs/spuc.html). Es decir, un prefijo, + algoritmo de hash, + el valor del hash a partir de dirección de correo.

**Comment by adriangmemorandum** [comment]
Acabo de hacer un nuevo commit con más cosillas: https://github.com/rediris-es/simplesamlphp-module-idpinstaller/commit/976e9db8e71bed5800399cb881fb99319653b988

Solo quedan dos detalles: 

- Lo del comentario en el valor `schacHomeOrganizationType` mejor lo dejamos para cuando tengamos tanto esto como la issue #4 en master. Esto dependera totalmente de la implementación de #4.

- Tema `eduPersonTargetId`: Viendo la documentación veo que estas son las diferentes formulas que podriamos implementar: 

```
sha256(userID + '@@' + targetID + '@@' + sourceID)
sha256(salt + '@@' + userID + '@@' + targetID + '@@' + sourceID + '@@' + salt)
sha256(salt + '@@' + mail + '@@' + targetID)
sha256(salt + '//' + userID + '//' + targetID + '//' + sourceID + '//' + salt)
'{new}' + sha256(salt + '@@' + userID + '@@' + targetID* + '@@' + sourceID + '@@' + salt)
```

El problema de todas ellas es que necesitan de `targetID`, y según comentaste en el email de momento no podemos disponer de dicho valor.

**Comment by lonoak** [comment]
Repaso ahora tras el merge...
