### ISSUE TITLE
Preguntar por el dominio de la organización, y utilizarlo para generación de valor de ciertos atributos

### ISSUE THREAD

**Issue by lonoak** [rediris-es/simplesamlphp-module-idp_installer#8]
Creo que no se está pidiendo el dominio principal de la organización (p. ej. `rediris.es`)... pienso que esto podría preguntarse en la [pantalla del paso 2 de 7, dentro del apartado 2.3](http://wiki.rediris.es/SIR2/IdP_de_referencia#Paso_2:_Configuraci.C3.B3n_b.C3.A1sica_del_sistema). El dominio debería validar un FQDN (por ejemplo [así](https://codereview.stackexchange.com/questions/140335/regex-for-domain-validation-name-validation), con javascript), y posteriormente se utilizaría para añadir la generación de determinados atributos que se _inyectan_ directamente en el IdP (no son atributos que se extraerán del repositorio de identidad.

Este cambio implicaría por tanto dos tareas:

- [x] solicitar el nombre de dominio, validarlo y almacenarlo para su uso posterior
- [x] insertarlo en atributos: `schacHomeOrganization`, y como dominio de scoping en atributos como `eduPersonScopedAffiliation` o `eduPersonPrincipalName`... no recuerdo si esta funcionalidad se añade en el saml20-idp-hosted.php, pero creo que ese sería el lugar indicado.

**Comment by adriangmemorandum** [comment]
Aquí puedes ver el primer paso completado: https://github.com/rediris-es/simplesamlphp-module-idpinstaller/commit/1f7ef2ac5fea4d751c883876d255a1c7a7a576c9

Siguiendo la linea del resto de campos de ese apartado, el dominio se almacena en un fichero temporal en primera instancia, y en los pasos siguientes se almacena en el fichero `saml20-idp-hosted.php`.

El resultado del fichero `saml20-idp-hosted.php` tras completar la instalación es el siguiente: 

```php

<?php

$metadata['idp-172.26.0.252'] = array(
        'UIInfo' => array(
            'DisplayName' => array(
                'en' => 'Memorandum Multimedia ',
                'es' => 'Memorandum Multimedia ',
                'gl' => 'Memorandum Multimedia ',
                'eu' => 'Memorandum Multimedia ',
                'ca' => 'Memorandum Multimedia ',
            ),
            'Description' => array(
                'en' => 'Memorandum Multimedia',
                'es' => 'Memorandum Multimedia',
                'gl' => 'Memorandum Multimedia',
                'eu' => 'Memorandum Multimedia',
                'ca' => 'Memorandum Multimedia',
            ),
            'InformationURL' => array(
                'en' => 'http://www.memorandum.net',
                'es' => 'http://www.memorandum.net',
                'gl' => 'http://www.memorandum.net',
                'eu' => 'http://www.memorandum.net',
                'ca' => 'http://www.memorandum.net',
            ),
            'Domain' => array(
                'en' => 'memorandum.net',
                'es' => 'memorandum.net',
                'gl' => 'memorandum.net',
                'eu' => 'memorandum.net',
                'ca' => 'memorandum.net',
            ),
        ),
        'host' => '__DEFAULT__',
        'privatekey' => '172.26.0.252.key.pem',
        'certificate' => '172.26.0.252.crt.pem',
        'auth' => '',
        'attributes.NameFormat' => 'urn:oasis:names:tc:SAML:2.0:attrname-format:uri',
       	'signature.algorithm' => 'http://www.w3.org/2001/04/xmldsig-more#rsa-sha256',
	'attributes' => array(
                'eduPersonTargetedID',
                'eduPersonAffiliation',
                'schacHomeOrganization',
                'eduPersonEntitlement',
                'schacPersonalUniqueCode',
                'uid',
                'mail',
                'displayName',
                'commonName',
                'eduPersonScopedAffiliation',
                'eduPersonPrincipalName',
                'schacHomeOrganizationType',
        ), 
        'authproc' => array(
            100 => array('class' => 'core:AttributeMap', 'name2oid'),
        ),
        'assertion.encryption' => true
    );

```

Eso es lo que se genera. Supongo que el segundo punto te refieres a los atributos que se añaden en ese mismo fichero, aunque se añaden sin ningún valor.

¿Deberiamos dar un valor a todos esos atributos? Quiza deberiamos realizar un analisis como el que hicimos por email en referencia a #7 (o finiquitarlo), ya que al final los atributos son los mismos.

**Comment by adriangmemorandum** [comment]
Por otro lado, he observado que en este proceso no se realiza ninguna validacion en cliente, solamente esta última que he añadido, pero quiza sería interesante validar que el nombre no es vacio, que las contraseñas son iguales... antes de enviarlo al servidor. 

Luego en el servidor si que se están validando, pero veo logico realizar la validación en los dos sitios. Si te parece le puedo dar una vuelta a eso.

**Comment by lonoak** [comment]
Sí a lo de la validación.

Lo de preguntar el dominio tiene dos usos:

- el de los metadatos (las extensiones de interfaz de usuario...)
- la generación del `schacHomeOrganization`... para eso habría que, o bien tocar aquí (no me gusta meter authprocs en el `config.php`, y ahora se está haciendo), o mejor, en el `saml20-idp-hosted.php`, pero ello requeriría nuevos desarrollos.

Tenemos que hablarlo.

**Comment by adriangmemorandum** [comment]
Listo el tema de las valicaciones JS, tanto en el paso 2 como en el paso 3: https://github.com/rediris-es/simplesamlphp-module-idpinstaller/commit/880a1fb64303a2015899c5bf78c18aa8c0b3721f

**Comment by lonoak** [comment]
Repaso ahora tras el merge
